[package]
name = "WorldWeaver"
description = "A powerful terrain generation tool that helps you generate procedural terrain to your liking, similar to minecraft"
version = "0.1.0"
license = "Apache-2.0"
authors = ["chickenMarinator"]
registry = "https://github.com/UpliftGames/wally-index"
realm = "shared"

[dev-dependencies]
